### ISSUE TITLE
issue with size

### ISSUE THREAD

**Issue by oldgt25** [HvRibbecK/EFT-Pak-ESP#5]
The bundle files are different sizes then the originals. this leads to the launcher detecting there's something wrong and then it will reinstall the old files back. In the  characters / prefabs

**Comment by HvRibbecK** [comment]
What is the size of the original files? It should be the same, but maybe they've changed it.

**Comment by vulcnFX** [comment]
The Prefabs folder in the files of the game has the size: 548,481,240 bytes
Your prefabs folder only has 466,508,221 bytes

**Comment by weird272** [comment]
How is this issue fixed?
I'm really new to this and just learning how to do this myself.

**Comment by vulcnFX** [comment]
It isnt fixed... We are waiting for HvRibbecK to fix it.

**Comment by weird272** [comment]
Ah okay so he's still works on this project?

**Comment by vulcnFX** [comment]
idk

**Comment by HvRibbecK** [comment]
Closed because no longer actively working on it.
